version: '3'

services:
  webgateway:
    image: webgateway:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webgateway$
    volumes:
      - C:\_git\core\src\WebGatewayCore\WebGateway\WebGateway:/app
      - C:\Users\malong\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_webgateway$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webgateway$ bin/Debug/netcoreapp2.0/WebGateway.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
