version: '3.1'
services:
  webgateway:
    container_name: web-server
    image: webgateway
    links:
      - orleans-silo
    depends_on:
      - orleans-silo
      
  tcpudpgateway:
    container_name: tcp-server
    image: tcpudpgateway
    ports:
      - "1883:1883/tcp"
      - "8883:8883/tcp"
      - "5683:5683/udp"
      - "5684:5684/tcp"
      - "5883:5883/udp"
    links:
      - orleans-silo
    depends_on:
      - orleans-silo
  orleans-silo:
    container_name: orleans-silo
    image: orleans-silo
    environment:
      - ORLEANS_DEPLOYMENT_ID: PiraeusDeployment 
      - ORLEANS_CLUSTER_DATACONNECTIONSTRING: DefaultEndpointsProtocol=https;AccountName=piraeus;AccountKey=Lfj8VJWQnIv79c2W1v+ptalPxqVOZyWUAV5m08ls/lrPs5/4Cb8xImbRgt3W9qngNeAEIP9Y1nQA6gk2uV2OiQ==;EndpointSuffix=core.windows.net
      - ORLEANS_STORAGE_PROVIDER: AzureBlobStore
      - ORLEANS_CONTAINER_NAME: orleans
      - ORLEANS_MAXMEMORY_STORAGE_GRAINS: 1000
      - ORLEANS_PROVIDER_DATACONNECTIONSTRING: DefaultEndpointsProtocol=https;AccountName=piraeus;AccountKey=Lfj8VJWQnIv79c2W1v+ptalPxqVOZyWUAV5m08ls/lrPs5/4Cb8xImbRgt3W9qngNeAEIP9Y1nQA6gk2uV2OiQ==;EndpointSuffix=core.windows.net
    ports:
      - "11111:11111/tcp"
      - "30000:30000/tcp"
networks:
  default:
    external:
      name: nat