version: '3.1'
services:
  webgateway:
    container_name: web-server
    image: webgateway
    depends_on:
      - orleans-silo
      
  tcpudpgateway:
    container_name: tcp-server
    image: tcpudpgateway
    ports:
      - "1883:1883/tcp"
      - "8883:8883/tcp"
      - "5683:5683/udp"
      - "5684:5684/tcp"
      - "5883:5883/udp"
    depends_on:
      - orleans-silo
  orleans-silo:
    container_name: orleans-silo
    image: orleans-silo
    ports:
      - "11111:11111/tcp"
      - "30000:30000/tcp"
networks:
  default:
    external:
      name: nat