version: '3.1'

services:
  tcpudpgateway:
    image: tcpudpgateway:latest
    build:
      context: ./TcpUdpGateway/Output/
      dockerfile: ./TcpUdpGateway/Dockerfile
    volumes: 
      - ./TcpUdpGateway/Output/:/app
    depends_on: 
      - orleans-silo
    ports:
      - "5000:1883"
  webgateway:
    image: webgateway:latest
    build:
      context: ./Webgateway/Output/
      dockerfile: ./Webgateway/Dockerfile
    volumes: 
      - ./Webgateway/Output/:/app
    depends_on: 
      - orleans-silo
  orleans-silo:
    image: orleans-silo:latest
    build:
      context: ./OrleansSilo/Output/
      dockerfile: ./OrleansSilo/Dockerfile
    volumes: 
      - ./OrleansSilo/Output/:/app