version: '3.1'
services:
  webgateway:
    container_name: web-server
    image: webgateway    
    networks:
      mynetwork:
        ipv4_address: 192.22.22.2    
    links:
      - orleans-silo
    depends_on:
      - orleans-silo
      
  tcpudpgateway:
    container_name: tcp-server
    image: tcpudpgateway    
    networks:
      mynetwork:
        ipv4_address: 192.22.22.3 
    ports:
      - "1883:1883/tcp"
      - "8883:8883/tcp"
      - "5683:5683/udp"
      - "5684:5684/tcp"
      - "5883:5883/udp"
    links:
      - orleans-silo
    depends_on:
      - orleans-silo
  orleans-silo:
    container_name: orleans-silo
    image: orleans-silo    
    networks:
      mynetwork:
        ipv4_address: 192.22.22.4
    ports:
      - "11111:11111/tcp"
      - "30000:30000/tcp"
networks:
  mynetwork:
    driver: transparent
    ipam:
      config:
      - subnet: 192.22.22.0/20